### ISSUE TITLE
zsh:1: permission denied: /tmp/tmux-buffer

### ISSUE THREAD

**Issue by raboof** [jbnicolai/tmux-urlview#11]
When I enter the hotkey, `zsh:1: permission denied: /tmp/tmux-buffer` flashes by (and then immediately disappears).

```
aengelen@yinka ~ % ls -alFh /tmp/tmux-buffer
-rw------- 1 aengelen aengelen 305 Jan  5 17:41 /tmp/tmux-buffer
```

(this is on linux, if it matters :) )

**Comment by raboof** [comment]
Might be because I have neither urlview neither extract_url installed - a friendlier error message would then be nice though

**Comment by raboof** [comment]
(jep seems that was it :) )

**Comment by jbnicolai** [comment]
Thanks for reporting, sorry for the late response on my part ;)
