### ISSUE TITLE
cannot open url to browser

### ISSUE THREAD

**Issue by AdrienLemaire** [jbnicolai/tmux-urlview#14]
UrlView opens when I press Ctrl-b-u, then pressing Enter on a link prints it as `URL: https://...` at the bottom of the pane.
But then, pressing Enter once more doesn't open the url in the browser. I currently need to to ctrl-b-[-space-b-o to select the url and open it from tmux-open.

I wish a simple Enter would do the same thing, and your gif suggests that this should be the default behavior. Any idea what might be broken ?

---

Arch Linux
termite v11
tmux 2.1
UrlView 0.9

**Comment by jbnicolai** [comment]
This should definitely be the default behavior. 

Could you try echoing a url to `urlview` outside tmux and see if that behaves as expected?

**Comment by AdrienLemaire** [comment]
hmm, you're right, it fails outside  tmux, and in different terminal. Setting the env BROWSER doesn't help either.

**Comment by s-kostyaev** [comment]
you need fix `/etc/urlview/system.urlview`

**Comment by AdrienLemaire** [comment]
correct, replacing `COMMAND url_handler.sh` with `COMMAND xdg-open` fixed the issue.

Thanks!

**Comment by sebdah** [comment]
Just for anyone else stumbling into this, an alternative to changing `/etc/urlview/system.urlview` is to add `~/.urlview` like this:

```
COMMAND firefox-developer-edition %s
```

**Comment by jtuz** [comment]
> correct, replacing `COMMAND url_handler.sh` with `COMMAND xdg-open` fixed the issue.
> 
> Thanks!



> you need fix `/etc/urlview/system.urlview`

It Work's!, thank you very much
