### ISSUE TITLE
Select URL when browsing a history

### ISSUE THREAD

**Issue by ghost** [jbnicolai/tmux-urlview#21]
I'm using Buku as my bookmark manager. Is there any chance that this plugin will not show only the last links on the screen but also those in history when in copy mode? Especially when I scroll through history and I have there eg 500+ links.

**Comment by dentuzhik** [comment]
Same here, sometimes links appear in multipage logs, and when invoking urlview, unfortunately, does not find links in current viewable screen, but it would be very convenient

**Comment by ghost** [comment]
It's limitation of urlview or extract_url, they can't read off screen.
Also all of them including tmux-urlview is long dead and unmaintained.
